# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Using Newton's method to find the root of a function
#' @description  Implement a function optimized using Newton's method to solve the roots of nonlinear equations
#' @param f Function that need to solve roots
#' @param df The derivative of function f
#' @param x0 Estimating the initial value of roots
#' @param maxiter Maximum number of iterations, default to 100
#' @param tol Error tolerance, used to determine the accuracy of the solution, defaults to 1e-6
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' f <- function(x) x^3 - x^2 - x - 1
#' df <- function(x) 3*x^2 - 2*x - 1
#' root <- newtonMethodC(f, df, x0 = 1.5)
#' print(root)
#' }
#' @export
newtonMethodC <- function(f, df, x0, maxiter = 100L, tol = 1e-6) {
    .Call('_SA23204194_newtonMethodC', PACKAGE = 'SA23204194', f, df, x0, maxiter, tol)
}

#' @title A function for implementing k-means clustering algorithm
#' @description Divide a set of observations into k clusters, so that each observation belongs to the nearest cluster center.
#' @param data dataset
#' @param k the number of clusters
#' @param maxIter Maximum number of iterations
#' @return A list containing two elements : centers and clusters
#' @examples
#' \dontrun{
#'     set.seed(194)
#'     data <- matrix(rnorm(100),ncol = 2)
#'     result <- kmeans_customR(data,3)
#' }
#' @export
kmeansC <- function(data, k, maxIter = 100L) {
    .Call('_SA23204194_kmeansC', PACKAGE = 'SA23204194', data, k, maxIter)
}

